name = "Create And Destroy"
author = "omo50"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a3f8039ccddb11b1795f210fdfd12226c21288c5822d9a4b5fa8b3d5936b2a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.129"

[options]
acceptable-game-versions = ["neoforge"]
